name: URL Shortener CI/CD

# 1. TRIGGER: When does this start?
on:
  push:
    branches: [ "main" ] # Runs every time you push to the 'main' branch
  pull_request:
    branches: [ "main" ] # Runs when someone tries to merge code into main

jobs:
  # --- JOB 1: BACKEND VALIDATION ---
  backend-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & Build Backend
        run: |
          cd back
          npm install
          # npm test  <-- (Commented out because default 'npm test' often fails without setup)

  # --- JOB 2: FRONTEND VALIDATION ---
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Angular App
        run: |
          cd front
          npm install
          npm run build -- --configuration=production

  # --- JOB 3: DOCKER BUILD (ONLY if testing & build pass) ---
  docker-images:
    needs: [backend-testing, frontend-build] # Wait for previous jobs to finish
    runs-on: ubuntu-latest
    if: github.event_name == 'push' # Only build images on actual pushes, not PRs
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Secret password from GitHub
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build/Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./back
          push: true
          tags: romdhani01/url-shortener-back:latest

      - name: Build/Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./front
          push: true
          tags: romdhani01/url-shortener-front:latest